kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: airsonic-pvc
  namespace: airsonic-helm
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi