apiVersion: v1
kind: PersistentVolume
metadata:
  name: airsonic-pv
  namespace: airsonic-helm
spec:
  capacity: 
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/airsonic-helm-config