apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels: 
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.image }}:{{ .Values.tag }}
        ports:
        - containerPort: 4040
        volumeMounts:
        - name: music
          mountPath: /flac
        - name: config
          mountPath: /config
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: Europe/London
      volumes:
      - hostPath:
          path: {{ .Values.music_path }}
        name: music
      - hostPath:
          path: {{ .Values.config_path }}
        name: config
